import { Inter } from "next/font/google";
import "./globals.css";
import Layoutui from "@/components/ui/Layoutui/Layoutui";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layoutui style={{ background: "#191919" }}>{children}</Layoutui>
      </body>
    </html>
  );
}
